@startuml
left to right direction

actor "Admin Pemasaran" as Admin
actor "Koki Produksi" as Koki
actor "Asisten Pengemasan" as Asisten
actor "Kurir" as Kurir

rectangle "Sistem Operasional Risolicious Mayo" {
  usecase "Menerima Pesanan" as UC1
  usecase "Menyiapkan Bahan Baku" as UC2
  usecase "Produksi Risoles" as UC3
  usecase "Pengemasan" as UC4
  usecase "Pengiriman Produk" as UC5
}

Admin --> UC1
Koki --> UC2
Koki --> UC3
Asisten --> UC4
Kurir --> UC5

@enduml